spring:

  datasource:

    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接URL
    url: jdbc:mysql://localhost:3306/lite_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&allowMultiQueries=true
    #数据库用户名
    username: root
    #数据库密码
    password: wyh246859
    #连接池类型
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      #连接池名称
      pool-name: Lite-Blog-Pool
      #最大连接数
      maximum-pool-size: 50
      #最小空闲连接
      minimum-idle: 10
      #最大超时过期时间
      max-lifetime: 1800000
      #连接超时时间
      connection-timeout: 30000
      idle-timeout: 30000
      #自动提交
      auto-commit: true

  #servlet配置
  servlet:
    #上传文件设置
    multipart:
      #最大接收20MB
      max-file-size: 20MB
      #最大请求20MB
      max-request-size: 20MB

  #语言配置
  messages:
    #编码
    encoding: UTF-8
    #默认名称
    basename: i18n.messages


  redis:
    #端口
    port: 6379
    #主机
    host: localhost
    #密码
    password: wyh246859
    #连接池
    lettuce:
      pool:
        # 最大连接数
        max-active: 100
        # 最大空闲连接
        max-idle: 20
        #最小空闲连接
        min-idle: 5
        #连接等待时间
        max-wait: 12000

  #热部署工具
  devtools:
    #重启
    restart:
      #是否开启
      enabled: true

  #邮件服务
  mail:
    #默认编码
    default-encoding: UTF-8
    #邮件服务器
    host: smtp.exmail.qq.com
    #用户名即发信邮箱
    username: vegetable-programmer@halfiisland.com
    #邮箱密码或者授权码
    password: password

  mvc:
    #打印请求细节
    log-request-details: true
    #跨域配置
    cors:
      #路径映射
      path-mapping: /**
      #允许的来源
      allowed-origins:
        - '*'
      #允许的header
      allowed-headers:
        - '*'
      #允许的请求方法
      allowed-methods:
        - POST
        - GET
        - PUT
        - OPTIONS
        - DELETE
      #开启验证 如果开启的话allowed-origins不能为*
      allowed-credentials: false
      max-age: 3600

    #拦截器配置
    interceptor:
      #是否开启拦截器默认是true，方便开发可以暂时关闭
      enable: true
      #access 放行url
      access-exclude:
        - /auth/login
        - /auth/register
        - /auth/refreshToken
        - /mail/sendAuthMail
        - /error
      #access 拦截url
      access-include:
        - /**
      #refesh 拦截url
      refresh-include:
        - /auth/refreshToken
      #refresh 放行url
      refresh-exclude:
        - /**
      cors-include:
        - /**


#mp配置
mybatis-plus:
  #xml扫描路径
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    #数据库配置
    db-config:
      #逻辑删除字段
      logic-delete-field: deleted
      #逻辑删除 false
      logic-not-delete-value: 0
      #逻辑删除 true
      logic-delete-value: 1
      #主键策略
      id-type: auto
  #sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.**.mapper

#mp的自动填充配置
auto-inject:
  #自动在插入时注入时间的字段名
  time-insert:
    - createdTime
    - updatedTime
    - uploadTime
  #自动在更新时注入时间的字段名
  time-update:
    - updatedTime


#服务器
server:
  #工作端口
  port: 8088
  #容器
  tomcat:
    #url编码
    uri-encoding: utf-8
  #错误重定向URL
  error:
    path: /error

  servlet:
    #默认容器路径/api开头
    context-path: /api
#日志
logging:
  #等级
  level:
    #debug级别会输出每个请求的详细情况，以及每个sql的执行细节
    com.liteweb: debug
    web: debug

#腾讯云COS服务
cos:
  # secretId secretKey 这两个是腾讯云永久密钥,泄露了的话就很麻烦，只能在控制台禁用了重写开个新的
  # 两个密钥平时推送代码的时候不要把这个也推了，除了部署上线的时候，开发时候都是自己用。
  appId: 1308755698
  #私钥id
  secretId: secretId
  #私钥
  secretKey: secretKey
  #地区归属
  region: ap-chongqing
  #连接超时时间
  connection-Timeout: 30000
  #Socket超时时间
  socket-timeout: 30000
  #线程池大小
  threadSizes: 32
  #分块上传阈值 20MB
  MultipartUploadThreshold: 4044121000
  #分块大小 2MB
  MinimumUploadPartSize: 2121440
  #URL
  BaseUrl: https://bucket-name.cos.ap-chongqing.myqcloud.com/
  #静态文件桶
  static-bucket: static-1308755698
  #公共桶
  public-bucket: public-1308755698
  #私有桶
  private-bucket: private-1308755698
  #日志桶
  log-bucket: log-1308755698
